module.exports = {
    printWidth: 80,
    tabWidth: 4,
    trailingComma: 'all',
    singleQuote: true,
    jsxBracketSameLine: true,
    semi: true,
    base: __dirname,
    importOrder: [
        'react',
        'react-router-dom',
        '<THIRD_PARTY_MODULES>',
        '^@server/(.*)$',
        '^@core/(.*)$',
        '^@ui/(.*)$',
        '^[./]',
    ],
    importOrderSeparation: true,
    importOrderSortSpecifiers: true,
};
